(function(){
  'use strict';
  const KEY='geodisSuite.userData.v2',LEGACY_KEY='geodisSuite.v1';
  const user={uid:getUserId(),displayName:'Operations Manager',mode:'local'};
  const today=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
  const seed={
    associates:[
      {id:'A10042',name:'James Dixon',role:'Material Handler',shift:'1st',department:'Warehouse Operations',status:'Active',quality:96,productivity:92,safety:100},
      {id:'A10057',name:'Samantha Keller',role:'Forklift Operator',shift:'2nd',department:'Warehouse Operations',status:'Active',quality:94,productivity:97,safety:100},
      {id:'A10063',name:'Robert Benton',role:'Yard Driver',shift:'1st',department:'Yard Operations',status:'Active',quality:89,productivity:91,safety:96},
      {id:'A10081',name:'Lisa Tran',role:'Inventory Clerk',shift:'1st',department:'Support Services',status:'Active',quality:98,productivity:95,safety:100},
      {id:'A10094',name:'Marcus Campbell',role:'Loader',shift:'3rd',department:'Warehouse Operations',status:'Active',quality:86,productivity:88,safety:93}
    ],
    attendance:[
      {id:'AT1',associateId:'A10042',date:today(),type:'Present',minutes:0,points:0,notes:''},
      {id:'AT2',associateId:'A10057',date:today(),type:'Late',minutes:18,points:.5,notes:'Traffic delay'},
      {id:'AT3',associateId:'A10063',date:today(),type:'Absent',minutes:480,points:1,notes:'No call'},
      {id:'AT4',associateId:'A10081',date:today(),type:'Present',minutes:0,points:0,notes:''}
    ],
    timeOff:[
      {id:'TO1',associateId:'A10042',type:'PTO',start:today(),end:today(),hours:8,status:'Approved'},
      {id:'TO2',associateId:'A10057',type:'Sick',start:today(),end:today(),hours:8,status:'Pending'},
      {id:'TO3',associateId:'A10081',type:'VTO',start:today(),end:today(),hours:4,status:'Approved'}
    ],
    attendanceSessions:[],
    requisitions:[
      {id:'REQ-2401',title:'Material Handler',department:'Warehouse Operations',shift:'1st',openings:12,filled:8,priority:'High',status:'Open',due:today()},
      {id:'REQ-2402',title:'Forklift Operator',department:'Warehouse Operations',shift:'2nd',openings:6,filled:4,priority:'Critical',status:'Open',due:today()},
      {id:'REQ-2403',title:'Yard Driver',department:'Yard Operations',shift:'1st',openings:3,filled:2,priority:'Medium',status:'Open',due:today()},
      {id:'REQ-2404',title:'Inventory Clerk',department:'Support Services',shift:'1st',openings:2,filled:2,priority:'Low',status:'Filled',due:today()}
    ]
  };
  let db=load(),view=new URLSearchParams(location.search).get('view')||'overview',query='',activeAttendanceSession=null;
  function getUserId(){let id=localStorage.getItem('geodisSuite.localUserId');if(!id){id='local_'+crypto.randomUUID();localStorage.setItem('geodisSuite.localUserId',id)}return id}
  function load(){try{const envelope=JSON.parse(localStorage.getItem(KEY)||'null');if(envelope?.users?.[user.uid])return Object.assign(structuredClone(seed),envelope.users[user.uid]);const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');return legacy?.associates?Object.assign(structuredClone(seed),legacy):structuredClone(seed)}catch(e){return structuredClone(seed)}}
  function save(){let envelope;try{envelope=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}if(!envelope)envelope={schemaVersion:2,users:{}};envelope.users[user.uid]=db;envelope.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(envelope))}
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icon=name=>({overview:'<path d="M3 11l9-8 9 8v9a1 1 0 01-1 1h-5v-7H9v7H4a1 1 0 01-1-1z"/>',associates:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0116 0"/>',attendance:'<rect x="3" y="5" width="18" height="16" rx="1"/><path d="M8 3v4m8-4v4M3 10h18m-13 5l2 2 5-5"/>',timeoff:'<path d="M3 12a9 9 0 0118 0H3zm9 0v9m-4 0h8"/>',requisitions:'<path d="M6 3h9l4 4v14H6zM14 3v5h5M9 13h7M9 17h7"/>',reconciliation:'<rect x="5" y="4" width="14" height="17" rx="1"/><path d="M9 4V2h6v2M8 9h8m-8 4h5m-5 4h7"/>'}[name]||'');
  const nav=[['overview','Overview'],['associates','Associates'],['attendance','Attendance'],['timeoff','Time Off'],['requisitions','Requisitions'],['reconciliation','Assignment Reconciliation']];
  function score(a){const pts=db.attendance.filter(x=>x.associateId===a.id).reduce((n,x)=>n+Number(x.points||0),0);return Math.max(0,Math.round((a.quality+a.productivity+a.safety)/3-pts*5))}
  function associate(id){return db.associates.find(a=>a.id===id)||{name:'Unknown',id:id}}
  function navHtml(){return `<aside class="suite-nav"><div class="suite-brand"><div class="suite-logo">G</div><div><strong>GEODIS</strong><small>MANAGEMENT SUITE</small></div></div><nav class="suite-nav-list">${nav.map(([id,label])=>`<button class="suite-nav-btn ${view===id?'active':''}" data-nav="${id}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor">${icon(id)}</svg><span>${label}</span></button>`).join('')}</nav><div class="suite-nav-footer">Workforce Management Suite<br>Local operations workspace · v1.0</div></aside>`}
  function headerHtml(){const labels={overview:['Overview','Workforce command center'],associates:['Active Associates','Performance scorecards'],attendance:['Attendance','Daily exceptions and points'],timeoff:['Time Off','PTO and VTO tracking'],requisitions:['Requisitions','Staffing demand and fulfillment']};const x=labels[view]||labels.overview;return `<header class="suite-top"><div class="suite-heading"><h1>${x[0]}</h1><p>${x[1]}</p></div><div class="suite-location">⌖ Atlanta DC (ATL01)⌄</div><div class="suite-user"><span><b>Operations Manager</b></span><div class="suite-avatar">OM</div></div></header>`}
  function metric(label,value,note,kind=''){return `<div class="metric"><div class="metric-icon ${kind}">${kind==='green'?'✓':kind==='orange'?'!':'#'}</div><div><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div></div>`}
  function overview(){const active=db.associates.filter(a=>a.status==='Active').length;const present=db.attendance.filter(x=>x.date===today()&&x.type==='Present').length;const rate=db.attendance.filter(x=>x.date===today()).length?Math.round(present/db.attendance.filter(x=>x.date===today()).length*100):100;const open=db.requisitions.filter(r=>r.status==='Open').reduce((n,r)=>n+(r.openings-r.filled),0);const pending=db.timeOff.filter(x=>x.status==='Pending').length;return `<div class="metric-strip">${metric('Active associates',active,'Current workforce')}${metric('Attendance rate',rate+'%',present+' present today','green')}${metric('PTO / VTO pending',pending,'Requests needing review')}${metric('Open positions',open,'Across active requisitions','orange')}</div><div class="suite-grid"><div class="suite-stack"><section class="suite-panel"><div class="suite-panel-head"><h2>Attendance rate trend</h2><div class="suite-actions"><button class="suite-btn" data-nav="attendance">View report</button></div></div><div class="trend-chart"><div class="goal-line"></div><svg class="trend-svg" viewBox="0 0 700 180" preserveAspectRatio="none"><polyline fill="none" stroke="#0b2c5b" stroke-width="3" points="0,48 116,41 233,53 350,49 466,91 583,59 700,53"/><g fill="#0b2c5b">${[[0,48],[116,41],[233,53],[350,49],[466,91],[583,59],[700,53]].map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="4"/>`).join('')}</g></svg><div class="trend-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Today</span></div></div><div class="chart-legend">– – Attendance goal: 92%</div></section><section class="suite-panel"><div class="suite-panel-head"><h2>Staffing & requisition coverage</h2><div class="suite-actions"><button class="suite-btn" data-nav="requisitions">View requisitions</button></div></div>${reqTable(db.requisitions.slice(0,4),true)}</section></div><div class="suite-stack"><section class="suite-panel"><div class="suite-panel-head"><h2>Time off activity</h2><div class="suite-actions"><button class="suite-btn" data-nav="timeoff">View all</button></div></div>${db.timeOff.slice(0,5).map(x=>activity(x)).join('')||empty('No time-off activity')}</section><section class="suite-panel"><div class="suite-panel-head"><h2>Operational action queue</h2></div>${alertRow(db.attendance.filter(x=>x.type==='Absent').length,'Absences recorded today')}${alertRow(pending,'Pending time-off approvals')}${alertRow(open,'Unfilled requisition positions')}${alertRow(db.associates.filter(a=>score(a)<90).length,'Scorecards below 90')}</section></div></div>`}
  function activity(x){const a=associate(x.associateId),initials=a.name.split(' ').map(n=>n[0]).join('').slice(0,2);return `<div class="activity-row"><div class="initial">${initials}</div><div><div class="row-title">${esc(a.name)}</div><div class="row-sub">${esc(x.start)} · ${x.hours} hours · ${esc(x.status)}</div></div><div class="row-type ${x.type==='VTO'?'vto':x.type==='Sick'?'sick':''}">${esc(x.type)}</div></div>`}
  function alertRow(n,label){return `<div class="alert-row"><div class="alert-num">${n}</div><div class="row-title">${label}</div><span>›</span></div>`}
  function empty(label){return `<div class="empty-module"><strong>${label}</strong>Add a record to begin tracking.</div>`}
  function moduleHero(title,sub,action,label){return `<div class="module-hero"><div><h2>${title}</h2><p>${sub}</p></div><button class="suite-btn primary" data-add="${action}">+ ${label}</button></div>`}
  function filters(){return `<div class="filter-row"><input class="suite-input" id="suite-search" value="${esc(query)}" placeholder="Search records…"><span style="margin-left:auto;color:var(--suite-muted);font-size:11px">${today()}</span></div>`}
  function associates(){const rows=db.associates.filter(a=>(a.name+a.id+a.role+a.department).toLowerCase().includes(query.toLowerCase()));return `${moduleHero('Associate performance','Quality, productivity, safety, and attendance in one score.','associate','Add associate')}<section class="suite-panel">${filters()}<div class="suite-table-wrap"><table class="suite-table"><thead><tr><th>Associate</th><th>Role / Department</th><th>Shift</th><th>Quality</th><th>Productivity</th><th>Safety</th><th>Attendance pts</th><th>Score</th><th></th></tr></thead><tbody>${rows.map(a=>{const pts=db.attendance.filter(x=>x.associateId===a.id).reduce((n,x)=>n+Number(x.points||0),0),s=score(a);return `<tr><td><div class="name">${esc(a.name)}</div><div class="sub">${esc(a.id)} · ${esc(a.status)}</div></td><td><div class="name">${esc(a.role)}</div><div class="sub">${esc(a.department)}</div></td><td>${esc(a.shift)}</td><td>${a.quality}%</td><td>${a.productivity}%</td><td>${a.safety}%</td><td>${pts}</td><td><span class="score ${s<80?'bad':s<90?'warn':''}">${s}</span></td><td><button class="suite-btn danger" data-delete="associate:${a.id}">Remove</button></td></tr>`}).join('')}</tbody></table></div></section>`}
  function normName(v){return String(v||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim().split(' ').sort().join(' ')}
  function normId(v){return String(v||'').replace(/\.0$/,'').replace(/[^a-z0-9]/gi,'').toUpperCase()}
  function findColumn(headers,terms){return headers.findIndex(h=>terms.some(t=>String(h||'').toLowerCase().includes(t)))}
  function normalizeRosterRows(rows,source){if(!rows.length)return[];let headerIndex=rows.findIndex(r=>r.some(c=>/name|associate|employee|badge|clock|id/i.test(String(c||''))));if(headerIndex<0)headerIndex=0;const headers=rows[headerIndex].map(String),badge=findColumn(headers,['badge','employee id','employee #','emp #','clock id','person id']),name=findColumn(headers,['employee name','associate name','full name','name']),first=findColumn(headers,['first name']),last=findColumn(headers,['last name']),time=findColumn(headers,['clock in','punch in','in time','time in']);return rows.slice(headerIndex+1).filter(r=>r.some(x=>String(x||'').trim())).map((r,i)=>{const full=name>=0?r[name]:[first>=0?r[first]:'',last>=0?r[last]:''].filter(Boolean).join(' ');return{row:i+headerIndex+2,badge:badge>=0?normId(r[badge]):'',name:String(full||'').trim(),time:time>=0?String(r[time]||''):'',source}}).filter(x=>x.badge||x.name)}
  function parsePasted(text){const lines=String(text||'').trim().split(/\r?\n/).filter(Boolean);return lines.map(line=>{const delim=line.includes('\t')?'\t':',';return line.split(delim).map(x=>x.trim().replace(/^"|"$/g,''))})}
  function reconcileSession(session){const clock=session.timeclockRows||[],client=session.clientRows||[],used=new Set(),matches=[];client.forEach(c=>{let idx=clock.findIndex((t,i)=>!used.has(i)&&c.badge&&t.badge===c.badge);if(idx<0)idx=clock.findIndex((t,i)=>!used.has(i)&&c.name&&normName(t.name)===normName(c.name));if(idx>=0){used.add(idx);matches.push({key:c.badge||normName(c.name),badge:c.badge||clock[idx].badge,name:c.name||clock[idx].name,status:'matched',clockTime:clock[idx].time,reason:''})}else matches.push({key:c.badge||normName(c.name),badge:c.badge,name:c.name,status:'client-only',clockTime:'',reason:''})});clock.forEach((t,i)=>{if(!used.has(i))matches.push({key:t.badge||normName(t.name),badge:t.badge,name:t.name,status:'clock-only',clockTime:t.time,reason:''})});const prior=Object.fromEntries((session.results||[]).map(x=>[x.key,x.reason]));matches.forEach(x=>x.reason=prior[x.key]||'');session.results=matches;session.updatedAt=new Date().toISOString();return session}
  function currentSession(){return db.attendanceSessions.find(x=>x.id===activeAttendanceSession)||null}
  function attendance(){const s=currentSession(),history=db.attendanceSessions.slice().reverse();return `${moduleHero('Daily attendance reconciliation','Compare timeclock punches with the client-maintained shift headcount.','attendance','Log manual event')}<div class="attendance-workflow"><section class="suite-panel workflow-setup"><div class="suite-panel-head"><h2>Shift setup</h2><span class="workflow-user">Saved for ${esc(user.displayName)}</span></div><div class="shift-fields"><label>Date<input class="suite-input" id="attendance-date" type="date" value="${esc(s?.date||today())}"></label><label>Shift<select class="suite-select" id="attendance-shift">${options(['1st','2nd','3rd'],s?.shift||'1st')}</select></label><button class="suite-btn primary" data-new-session>${s?'New reconciliation':'Start reconciliation'}</button></div></section><div class="workflow-sources"><section class="suite-panel source-panel"><div class="source-step">1</div><h3>Upload timeclock report</h3><p>Excel, CSV, or TSV. Badge, employee name, and clock-in columns are detected automatically.</p><input type="file" id="timeclock-file" accept=".xlsx,.xls,.csv,.tsv" hidden><button class="suite-btn" data-upload-timeclock>${s?.timeclockRows?.length?'Replace file':'Choose spreadsheet'}</button>${s?.timeclockRows?.length?`<div class="source-loaded"><b>${s.timeclockRows.length}</b> clock records · ${esc(s.timeclockFile||'Uploaded report')}</div>`:''}</section><section class="suite-panel source-panel"><div class="source-step">2</div><h3>Paste client headcount</h3><p>Copy the used range from the client’s shift spreadsheet and paste it below.</p><textarea id="client-paste" placeholder="Badge\tAssociate Name\tShift\nA10042\tJames Dixon\t1st">${esc(s?.clientPaste||'')}</textarea><button class="suite-btn" data-parse-client>Use pasted rows</button>${s?.clientRows?.length?`<div class="source-loaded"><b>${s.clientRows.length}</b> client rows parsed</div>`:''}</section></div>${s?reconciliationResults(s):'<div class="workflow-empty">Start a reconciliation, then add both sources to compare the shift.</div>'}</div><section class="suite-panel attendance-history"><div class="suite-panel-head"><h2>Recent shift reconciliations</h2></div>${history.length?`<div class="suite-table-wrap"><table class="suite-table"><thead><tr><th>Date</th><th>Shift</th><th>Timeclock</th><th>Client headcount</th><th>Exceptions</th><th>Updated</th><th></th></tr></thead><tbody>${history.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.shift)}</td><td>${x.timeclockRows?.length||0}</td><td>${x.clientRows?.length||0}</td><td>${(x.results||[]).filter(r=>r.status!=='matched').length}</td><td>${new Date(x.updatedAt||x.createdAt).toLocaleString()}</td><td><button class="suite-btn" data-open-session="${x.id}">Open</button></td></tr>`).join('')}</tbody></table></div>`:empty('No reconciliations yet')}</section>`}
  function reconciliationResults(s){if(!s.timeclockRows?.length&&!s.clientRows?.length)return'<div class="workflow-empty">Add the timeclock report and client headcount to begin.</div>';if(!s.timeclockRows?.length||!s.clientRows?.length)return`<div class="workflow-empty">${s.timeclockRows?.length?'Paste the client headcount to compare.':'Upload the timeclock report to compare.'}</div>`;const results=s.results||[],matched=results.filter(x=>x.status==='matched').length,clientOnly=results.filter(x=>x.status==='client-only').length,clockOnly=results.filter(x=>x.status==='clock-only').length;return `<section class="suite-panel reconciliation-results"><div class="suite-panel-head"><h2>Shift comparison</h2><div class="result-counts"><span><b>${matched}</b> matched</span><span class="warn"><b>${clientOnly}</b> missing punch</span><span><b>${clockOnly}</b> not on client list</span></div></div><div class="suite-table-wrap"><table class="suite-table"><thead><tr><th>Associate</th><th>Badge</th><th>Result</th><th>Clock in</th><th>Call-off / exception reason</th></tr></thead><tbody>${results.map(x=>`<tr class="result-${x.status}"><td class="name">${esc(x.name||'Unknown')}</td><td>${esc(x.badge||'—')}</td><td><span class="status ${x.status==='matched'?'':x.status==='client-only'?'closed':'pending'}">${x.status==='matched'?'On both':x.status==='client-only'?'No timeclock punch':'Not on client list'}</span></td><td>${esc(x.clockTime||'—')}</td><td><input class="suite-input reason-input" data-reason="${esc(x.key)}" value="${esc(x.reason||'')}" placeholder="Search call-offs, then enter reason…"></td></tr>`).join('')}</tbody></table></div><div class="result-footer"><span>Reasons save automatically to this user’s shift record.</span><button class="suite-btn" data-copy-report>Copy client-ready summary</button></div></section>`}
  function timeoff(){const rows=db.timeOff.filter(x=>{const a=associate(x.associateId);return (a.name+a.id+x.type+x.status).toLowerCase().includes(query.toLowerCase())});return `${moduleHero('PTO / VTO tracking','Manage requests and keep attendance records aligned.','timeoff','New request')}<section class="suite-panel">${filters()}<div class="suite-table-wrap"><table class="suite-table"><thead><tr><th>Associate</th><th>Type</th><th>Dates</th><th>Hours</th><th>Status</th><th>Attendance tie-in</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td><div class="name">${esc(associate(x.associateId).name)}</div><div class="sub">${esc(x.associateId)}</div></td><td><span class="row-type ${x.type==='VTO'?'vto':x.type==='Sick'?'sick':''}">${esc(x.type)}</span></td><td>${esc(x.start)} → ${esc(x.end)}</td><td>${x.hours}</td><td><span class="status ${x.status==='Pending'?'pending':x.status==='Denied'?'closed':''}">${esc(x.status)}</span></td><td>${x.status==='Approved'?'Excused / 0 points':'Not posted'}</td><td><button class="suite-btn" data-toggle="${x.id}">${x.status==='Pending'?'Approve':'Set pending'}</button> <button class="suite-btn danger" data-delete="timeoff:${x.id}">Remove</button></td></tr>`).join('')}</tbody></table></div></section>`}
  function reqTable(rows,compact){return `<div class="suite-table-wrap"><table class="suite-table"><thead><tr><th>Requisition</th><th>Department</th><th>Shift</th><th>Positions</th><th>Filled</th><th>Coverage</th>${compact?'':'<th>Priority</th><th>Status</th><th></th>'}</tr></thead><tbody>${rows.map(r=>{const pct=Math.round(r.filled/r.openings*100);return `<tr><td><div class="name">${esc(r.title)}</div><div class="sub">${esc(r.id)}</div></td><td>${esc(r.department)}</td><td>${esc(r.shift)}</td><td>${r.openings}</td><td>${r.filled}</td><td><span class="score ${pct<70?'bad':pct<90?'warn':''}">${pct}%</span></td>${compact?'':`<td>${esc(r.priority)}</td><td><span class="status ${r.status==='Filled'?'closed':''}">${esc(r.status)}</span></td><td><button class="suite-btn" data-fill="${r.id}">+ Fill</button> <button class="suite-btn danger" data-delete="requisition:${r.id}">Remove</button></td>`}</tr>`}).join('')}</tbody></table></div>`}
  function requisitions(){const rows=db.requisitions.filter(r=>(r.id+r.title+r.department+r.shift+r.priority+r.status).toLowerCase().includes(query.toLowerCase()));return `${moduleHero('Requisition tracking','Track hiring demand from opening through fulfillment.','requisition','New requisition')}<section class="suite-panel">${filters()}${reqTable(rows,false)}</section>`}
  function render(){if(view==='reconciliation'){document.body.classList.remove('suite-active');return}document.body.classList.add('suite-active');const content={overview,associates,attendance,timeoff,requisitions}[view]();document.getElementById('suite-root').innerHTML=`<div class="suite-layout">${navHtml()}<div class="suite-main">${headerHtml()}<main class="suite-content">${content}</main></div></div>`}
  function options(list,current){return list.map(x=>`<option ${x===current?'selected':''}>${esc(x)}</option>`).join('')}
  function associateOptions(){return db.associates.map(a=>`<option value="${esc(a.id)}">${esc(a.name)} · ${esc(a.id)}</option>`).join('')}
  function modal(type){let fields='';if(type==='associate')fields=`${field('Name','name','text','',true)}${field('Badge / ID','id','text','',true)}${field('Role','role','text','',true)}${field('Department','department','select',['Warehouse Operations','Yard Operations','Transportation','Support Services'])}${field('Shift','shift','select',['1st','2nd','3rd'])}${field('Quality %','quality','number','95')}${field('Productivity %','productivity','number','95')}${field('Safety %','safety','number','100')}`;if(type==='attendance')fields=`${field('Associate','associateId','custom',associateOptions())}${field('Date','date','date',today())}${field('Status','type','select',['Present','Late','Absent','Early Out'])}${field('Minutes','minutes','number','0')}${field('Policy points','points','number','0')}${field('Notes','notes','text','')}`;if(type==='timeoff')fields=`${field('Associate','associateId','custom',associateOptions())}${field('Type','type','select',['PTO','VTO','Sick','Personal'])}${field('Start','start','date',today())}${field('End','end','date',today())}${field('Hours','hours','number','8')}${field('Status','status','select',['Pending','Approved','Denied'])}`;if(type==='requisition')fields=`${field('Req ID','id','text','REQ-'+Math.floor(2400+Math.random()*500),true)}${field('Job title','title','text','',true)}${field('Department','department','select',['Warehouse Operations','Yard Operations','Transportation','Support Services'])}${field('Shift','shift','select',['1st','2nd','3rd'])}${field('Openings','openings','number','1')}${field('Filled','filled','number','0')}${field('Priority','priority','select',['Low','Medium','High','Critical'])}${field('Due date','due','date',today())}`;document.body.insertAdjacentHTML('beforeend',`<div class="suite-modal-backdrop" id="suite-modal"><div class="suite-modal"><div class="suite-modal-head"><h3>${type==='timeoff'?'New time-off request':'Add '+type}</h3><button class="suite-btn" data-close>×</button></div><form class="suite-form" data-form="${type}">${fields}<div class="suite-modal-actions"><button type="button" class="suite-btn" data-close>Cancel</button><button class="suite-btn primary">Save record</button></div></form></div></div>`)}
  function field(label,name,type,value,required){let input;if(type==='select')input=`<select name="${name}">${options(value)}</select>`;else if(type==='custom')input=`<select name="${name}">${value}</select>`;else input=`<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='number'?'min="0" step="0.5"':''}>`;return `<label class="suite-field"><span>${label}</span>${input}</label>`}
  document.addEventListener('click',async e=>{if(e.target.closest('[data-new-session]')){const date=document.getElementById('attendance-date').value||today(),shift=document.getElementById('attendance-shift').value,session={id:'AS'+Date.now(),ownerId:user.uid,date,shift,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),timeclockRows:[],clientRows:[],clientPaste:'',results:[]};db.attendanceSessions.push(session);activeAttendanceSession=session.id;save();render();return}if(e.target.closest('[data-upload-timeclock]')){document.getElementById('timeclock-file').click();return}if(e.target.closest('[data-parse-client]')){const s=currentSession();if(!s){alert('Start a reconciliation first.');return}const text=document.getElementById('client-paste').value,srows=normalizeRosterRows(parsePasted(text),'client');if(!srows.length){alert('No usable rows were found. Include a header row with a name or badge column.');return}s.clientPaste=text;s.clientRows=srows;reconcileSession(s);save();render();return}const open=e.target.closest('[data-open-session]');if(open){activeAttendanceSession=open.dataset.openSession;render();scrollTo(0,0);return}if(e.target.closest('[data-copy-report]')){const s=currentSession(),exceptions=(s.results||[]).filter(x=>x.status!=='matched'),lines=[`GEODIS On-Premise Attendance · ${s.date} · ${s.shift} Shift`,`Timeclock records: ${s.timeclockRows.length} | Client headcount: ${s.clientRows.length} | Exceptions: ${exceptions.length}`,'',...exceptions.map(x=>`${x.name||'Unknown'} (${x.badge||'no badge'}) — ${x.status==='client-only'?'No timeclock punch':'Not on client list'}${x.reason?' — '+x.reason:''}`)];await navigator.clipboard.writeText(lines.join('\n'));e.target.closest('[data-copy-report]').textContent='Copied';return}});
  document.addEventListener('change',e=>{if(e.target.id!=='timeclock-file'||!e.target.files[0])return;const s=currentSession();if(!s){alert('Start a reconciliation first.');return}const file=e.target.files[0],reader=new FileReader();reader.onload=ev=>{try{const wb=XLSX.read(ev.target.result,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''}),normalized=normalizeRosterRows(rows,'timeclock');if(!normalized.length)throw new Error('No name or badge records were detected.');s.timeclockFile=file.name;s.timeclockRows=normalized;reconcileSession(s);save();render()}catch(err){alert('Could not read the timeclock report: '+err.message)}};reader.readAsArrayBuffer(file)});
  document.addEventListener('input',e=>{if(e.target.matches('[data-reason]')){const s=currentSession(),row=s?.results?.find(x=>x.key===e.target.dataset.reason);if(row){row.reason=e.target.value;s.updatedAt=new Date().toISOString();save()}}});
  document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n){view=n.dataset.nav;query='';if(view==='attendance'&&!activeAttendanceSession&&db.attendanceSessions.length)activeAttendanceSession=db.attendanceSessions[db.attendanceSessions.length-1].id;render();scrollTo(0,0);return}if(e.target.closest('[data-add]')){modal(e.target.closest('[data-add]').dataset.add);return}if(e.target.closest('[data-close]')){e.target.closest('.suite-modal-backdrop').remove();return}const d=e.target.closest('[data-delete]');if(d){const [type,id]=d.dataset.delete.split(':');const map={associate:'associates',attendance:'attendance',timeoff:'timeOff',requisition:'requisitions'};if(type==='associate'&&(db.attendance.some(x=>x.associateId===id)||db.timeOff.some(x=>x.associateId===id))&&!confirm('This associate has linked records. Remove the associate anyway?'))return;db[map[type]]=db[map[type]].filter(x=>x.id!==id);save();render();return}const t=e.target.closest('[data-toggle]');if(t){const x=db.timeOff.find(x=>x.id===t.dataset.toggle);x.status=x.status==='Pending'?'Approved':'Pending';save();render();return}const f=e.target.closest('[data-fill]');if(f){const r=db.requisitions.find(x=>x.id===f.dataset.fill);r.filled=Math.min(r.openings,r.filled+1);if(r.filled===r.openings)r.status='Filled';save();render()}});
  document.addEventListener('input',e=>{if(e.target.id==='suite-search'){query=e.target.value;render();const i=document.getElementById('suite-search');i.focus();i.setSelectionRange(query.length,query.length)}});
  document.addEventListener('submit',e=>{const form=e.target.closest('[data-form]');if(!form)return;e.preventDefault();const type=form.dataset.form,data=Object.fromEntries(new FormData(form));['quality','productivity','safety','minutes','points','hours','openings','filled'].forEach(k=>{if(k in data)data[k]=Number(data[k])});data.id=data.id||type.slice(0,2).toUpperCase()+Date.now();if(type==='associate'){data.status='Active';db.associates.push(data)}if(type==='attendance')db.attendance.unshift(data);if(type==='timeoff')db.timeOff.unshift(data);if(type==='requisition'){data.status=data.filled>=data.openings?'Filled':'Open';db.requisitions.unshift(data)}save();document.getElementById('suite-modal').remove();render()});
  window.addEventListener('keydown',e=>{if(e.key==='Escape'){const m=document.getElementById('suite-modal');if(m)m.remove()}if(e.key==='Home'&&!document.body.classList.contains('suite-active')){view='overview';render()}});
  window.GEODISSuite={open:()=>{view='overview';render()},reset:()=>{db=structuredClone(seed);save();render()},parsePastedHeadcount:text=>normalizeRosterRows(parsePasted(text),'client')};
  document.body.insertAdjacentHTML('beforeend','<button class="suite-return" type="button">← Back to management suite</button>');
  document.querySelector('.suite-return').addEventListener('click',()=>{view='overview';render()});
  render();
})();
