/* The on-premise export filtered to "On Premises = Yes": it lists only who is
   on premise, so being absent from it means not clocked in -- not "no timeclock
   record", which is what absence from the full export means. Names here are
   made up; the layout, preamble included, is the real export's. */
const XLSX = require('xlsx');
const S = require('../schedule-core.js');
let pass = 0, fail = 0;
const t = (n, c) => { if (c) pass++; else { fail++; console.log('  FAIL: ' + n); } };

const CSV = [
  'Export Name:,On Premises - Simple',
  'Generated By:,Test User',
  'Time Period:,Today',
  'Location:,All Home',
  'Filtered By:,On Premises(Yes )',
  'Total Rows:,5',
  'Currency:,NONE',
  '',
  'On Premises,Employee Full Name & ID,Reports To,Primary location (path)',
  'True,"Able, Ann (80-AABLE1111)","Boss, One",GEODIS/US/CL/CLSCEN/CLSL/CL1541/1541',
  'True,"Baker, Bo (80-BBAKER2222)","Boss, Two",GEODIS/US/CL/CLSCEN/CLSL/CL1523/1523',
  'True,"Cole, Cy (80-CCOLE3333)","Boss, Two",GEODIS/US/CL/CLSCEN/CLSL/CL1523/1523',
  'True,"Dunn, Di (80-DDUNN4444)","Boss, Three",GEODIS/US/CL/CLSCEN/CLSL/CL1554/1554',
  'True,"O\'Hare, Ed (80-EO\'HAR5555)","Boss, Two",GEODIS/US/CL/CLSCEN/CLSL/CL1523/1523'
].join('\n');
// The browser reads the upload the same way: XLSX on the file, first sheet.
const aoaOf = text => {
  const wb = XLSX.read(text, { type: 'string' });
  return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1, raw: false, defval: '' });
};

console.log('— reading the filtered export —');
const p = S.parseOnPremise(aoaOf(CSV));
t('the preamble is not read as people', p.people.length === 5 && !p.people.some(x => /:$/.test(x.name) || x.name === 'True'));
t('no warnings', p.warnings.length === 0);
t('names and ids', p.people[0].name === 'Able, Ann' && p.people[0].wfmId === '80-AABLE1111');
t('an apostrophe in the id survives', p.people[4].wfmId === "80-EO'HAR5555");
t('manager and location', p.people[1].manager === 'Boss, Two' && /1523$/.test(p.people[1].location));
t('everyone is present', p.people.every(x => x.present));
t('the filter is read from the preamble', /On Premises\(Yes/.test(p.filter));
t('so it is a present-only export', p.presentOnly === true);
t('and covers the sites it names', p.sites.join() === '1523,1541,1554');

console.log('— the full export is unchanged —');
const full = S.parseOnPremise([
  ['On Premises', 'Employee Full Name & ID', 'Reports To', 'Primary location (path)'],
  ['True', 'Able, Ann (80-AABLE1111)', 'Boss', 'X/1523'],
  ['False', 'Baker, Bo (80-BBAKER2222)', 'Boss', 'X/1523']
]);
t('still read', full.people.length === 2 && full.people[1].present === false);
t('and not present-only', full.presentOnly === false);
t('a full export where everyone happens to be in is NOT present-only', S.parseOnPremise([
  ['On Premises', 'Employee Full Name & ID'], ['True', 'Able, Ann (80-AABLE1111)']]).presentOnly === false);

console.log('— coverage from a present-only export —');
const today = '2026-10-01', at = new Date(2026, 9, 1, 10, 0);
const shift = (start, end) => ({ [today]: { start, end, raw: '', overnight: false } });
const person = (name, loc, shifts, eid) => ({ name, nameKey: S.nameKey(name), location: loc, shifts, eid });
const schedule = { dates: [today], people: [
  person('Baker, Bo', '1523', shift(360, 870), '80-BBAKER2222'),  // on shift, listed: working
  person('Gone, Gus', '1523', shift(360, 870)),                    // on shift, not listed: NOT CLOCKED IN
  person('Late, Lou', '1541', shift(900, 1380)),                   // later today, not listed: scheduled
  person('Fresh, Fay', '1554', shift(595, 1100)),                  // started 5 min ago: inside grace
  person('Done, Dee', '1523', shift(0, 300)),                      // ended, not listed: complete
  person('Chi, Cal', '1502', shift(360, 870))                      // a site the export does not cover
] };
const r = S.buildCoverage({ schedule, presence: p, asOf: at });
const st = name => (r.rows.find(x => x.name === name) || {}).status;
t('listed and on shift is working', st('Baker, Bo') === 'working');
t('missing from the export while on shift is NOT clocked in', st('Gone, Gus') === 'missing');
t('never "not in timeclock" -- the export only lists who is in', !r.rows.some(x => x.status === 'notInReport'));
t('a later shift is just scheduled', st('Late, Lou') === 'scheduled');
t('inside the grace window is starting', st('Fresh, Fay') === 'starting');
t('a finished shift is complete', st('Done, Dee') === 'complete');
t('a site the export does not cover is set aside, not missing', !st('Chi, Cal') && r.overlap.outOfScope === 1 &&
  r.overlap.outOfScopeSites.join() === '1502');
t('listed with no shift is unscheduled', st('Able, Ann') === 'unscheduled' && st('Dunn, Di') === 'unscheduled');
t('coverage counts only the sites it covers', r.summary.coverage === 33);   // Baker of Baker, Gone, Fresh
t('a low match is not warned about -- it is normal before a shift', !r.warnings.some(w => /Only \d+ of/.test(w)));
t('not a mismatch', r.mismatch === false);

console.log('— the wrong area altogether —');
const chicago = { dates: [today], people: [person('Chi, Cal', '1502', shift(360, 870)), person('Chi, Cy', '1519', shift(360, 870))] };
const m = S.buildCoverage({ schedule: chicago, presence: p, asOf: at });
t('a schedule with nobody at the export\'s sites is a mismatch', m.mismatch === true && m.summary.coverage === null);
t('and says which sites each covers', /covers 1523, 1541, 1554/.test(m.warnings[0]) && /schedule covers 1502, 1519/.test(m.warnings[0]));
t('nobody is reported missing', !m.rows.some(x => x.status === 'missing'));

console.log('— matching on the id beats the name —');
const renamed = { dates: [today], people: [person('Baker-Smith, Bo', '1523', shift(360, 870), '80-BBAKER2222')] };
t('found by EID despite a different name', S.buildCoverage({ schedule: renamed, presence: p, asOf: at }).rows
  .find(x => x.name === 'Baker-Smith, Bo').status === 'working');

console.log('\n' + pass + ' passed, ' + fail + ' failed');
if (fail) process.exit(1);
